version: "3.3"

services:
  rbback:
    build: ./rbback
    environment:
      - HOST=example.com
    volumes:
      - static_volume:/app/backend/rbback/static
      - media_volume:/app/backend/rbback/media
    networks:
      - nginx_network
      - database_network
    depends_on:
      - database
    restart: always
    secrets:
      - secret_key
      - postgres_password

  rbfront:
    build:
      context: ./rbfront
      dockerfile: Dockerfile
    volumes:
      - rbfront_volume:/app/frontend/build
    depends_on:
      - rbback
    environment:
      REACT_APP_SITE_NAME: "Rasberry Heaven"

  nginx:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Helsinki
      - URL=example.com
      - DHLEVEL=4096
      - STAGING=True
    volumes:
      - nginx_volume:/config
      - ./nginx/prod/:/config/nginx/site-confs:ro
      - static_volume:/app/backend/rbback/static
      - media_volume:/app/backend/rbback/media
      - rbfront_volume:/app/frontend/build
    depends_on:
      - rbback
      - rbfront
      - database
    restart: always
    networks:
      - nginx_network

  database:
    image: postgres:12-alpine
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: "rbback"
      POSTGRES_DB: "rbback"
    restart: always
    secrets:
      - postgres_password

networks:
  nginx_network:
  database_network:

volumes:
  database_volume:
  static_volume:
  media_volume:
  rbfront_volume:
  nginx_volume:

secrets:
  postgres_password:
    file: password.txt
  secret_key:
    file: key.txt
